// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web; // Use web configuration for Windows
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvSUzJz9u6r8r4RsKh1TnyYVC2VjCYTLE',
    appId: '1:366792053793:web:2753824de016fe34667f60',
    messagingSenderId: '366792053793',
    projectId: 'zoom-classroom-f77fc',
    authDomain: 'zoom-classroom-f77fc.firebaseapp.com',
    storageBucket: 'zoom-classroom-f77fc.firebasestorage.app',
    measurementId: 'G-LVRK57031Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKkA3rZhgQE0BoDdoy_gBQjd4jf45wcRI',
    appId: '1:366792053793:android:0b17fff8c2dbe308667f60',
    messagingSenderId: '366792053793',
    projectId: 'zoom-classroom-f77fc',
    storageBucket: 'zoom-classroom-f77fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzovQURUpiTnZZ48E2NN32-ENzDYmqZ2c',
    appId: '1:366792053793:ios:79f3b4863d23601d667f60',
    messagingSenderId: '366792053793',
    projectId: 'zoom-classroom-f77fc',
    storageBucket: 'zoom-classroom-f77fc.firebasestorage.app',
    androidClientId: '366792053793-fvo1lu71dq4tns2v3ertdrok74l4sa3c.apps.googleusercontent.com',
    iosClientId: '366792053793-0irajambu3mqets7rj89duf9h95ngfs7.apps.googleusercontent.com',
    iosBundleId: 'com.classroom.zoom',
  );
}
